### ISSUE TITLE
codeready-toolchain/toolchain-operator=master has required jobs but has protect: false

### ISSUE THREAD

**Issue by droslean** [openshift/release#6178] opened 2019-12-02 10:27 UTC
```console
{"component":"tide","file":"prow/config/branch_protection.go:257","func":"k8s.io/test-infra/prow/config.(*Config).GetPolicy","level":"warning","msg":"codeready-toolchain/toolchain-operator=master has required jobs but has protect: false","time":"2019-12-02T10:07:24Z"}
```

**Comment by stevekuznetsov** [comment] 2019-12-02 18:18
This is a dupe of https://github.com/openshift/release/issues/6064 (and did not have the triage label)

/close

**Closed by stevekuznetsov** 2019-12-02 18:18 UTC
